print("Hello, world")
print(type("Hello, world"))
print("Hello2,"+'world33')
print(True, False)
print(type(True), type(1.2))
print(5<=10, 5>=10)
print("5")
print(type('5'))
print(int('5'))
print(type(int('5')))